Description = "Noodles is an opinionated project manager"
License = "Apache-2.0"
Name = "Noodles"
Version = 0.1

[Projects]
  [Projects.noodles]
  Binary = true
  Destination = "build/noodles"
  Plugin = "go"
  Source = "src/noodles/*.go"

  [Projects.noodlestest]
  Binary = true
  Destination = "build/test-recursion/noodles"
  Plugin = "go"
  Source = "src/noodles/*.go"