Description = "Noodles is an opinionated project manager"
License = "Apache-2.0"
Name = "Noodles"
Version = 0.1

[Projects]
	[Projects.exampleless]
		Destination = "build/less/example.css"
		Plugin = "less"
		Source = "src/less/example.less"
	[Projects.exampletypescript]
		Compress = true
		Destination = "build/typescript/example.js"
		Mode = "advanced"
		Plugin = "typescript"
		Source = "src/typescript/example/example.ts"
		Target = "ES5"
	[Projects.noodles]
		Destination = "build/noodles"
		Plugin = "go"
		Source = "src/noodles/*.go"
	[Projects.noodlestest]
		Destination = "build/test-recursion/noodles"
		Plugin = "go"
		Source = "src/noodles/*.go"
		TarballLocation = "test-recursion/"

[Scripts]
	[Scripts.argtest]
		Arguments = ["build/"]
		Description = "Script to test basic argument passing."
		Exec = "ls"
	[Scripts.dirnoexist]
		Description = "Script to test directory change failure."
		Directory = "idontexist"
		Exec = "weshouldnevercallthis"
	[Scripts.dirpwd]
		Description = "Script to test basic directory changing."
		Directory = "build"
		Exec = "pwd"
	[Scripts.testfile]
		File = "build/testoutput"
		Exec = "ls"
		Redirect = true
	[Scripts.whoami]
		Description = "Script to test basic exec call by running whoami."
		Exec = "whoami"