Description = "Noodles is an opinionated project manager"
License = "Apache-2.0"
Name = "Noodles"
Version = 0.1

[Projects]
	[Projects.exampleless]
		Destination = "build/less/example.css"
		Plugin = "less"
		Source = "src/less/example.less"
	[Projects.exampletypescript]
		Compress = true
		Destination = "build/typescript/example.js"
		Plugin = "typescript"
		Source = "src/typescript/example/example.ts"
		Target = "ES5"
	[Projects.noodles]
		Destination = "build/noodles"
		Plugin = "go"
		Source = "src/noodles/*.go"
	[Projects.noodlestest]
		Destination = "build/test-recursion/noodles"
		Plugin = "go"
		Source = "src/noodles/*.go"
		TarballLocation = "test-recursion/"
